### ISSUE TITLE
❤贺兰星辰❤

### ISSUE THREAD

**Issue by Subilan** [shaokeyibb/LYCJudgement#1]
This must be awesome! Hope to see the progress in the future.

---

By the way, there is a misspelling in the `README.md`

![image](https://user-images.githubusercontent.com/36447840/80980223-f5c8cd80-8e5a-11ea-9472-efcb5da8c422.png)

**Comment by Subilan** [comment]
❤Celebration Blue Star Morning❤ Mother 々 Love You

**Comment by Karlatemp** [comment]
wwwwwwwwwwwwwww

**Comment by Sakurallin** [comment]
Year,i think it's a good plugin.But can it add a timing kick function?
